varexpress=require('express');
varapp=express();
varmysql=require('mysql');
app.set('viewengine','pug');
app.set('views','./views');
varcon=mysql.createConnection({
host:"45.55.136.114",
user:"csc3610",
password:"csc3610",
database:"csc3610"
});
varbodyParser=require('body-parser');
varmulter=require('multer');
const{platform}=require('os');
varupload=multer();
//forparsingapplication/json
app.use(bodyParser.json());
//forparsingapplication/xwww-
app.use(bodyParser.urlencoded({extended:true}));
//form-urlencoded
app.post('/candy',function(req,res){
letitem=req.body.item;
letcount=req.body.count;
letcost=req.body.cost;
lettotalValue=count*cost;
res.send(`recievedyourrequest.<br/>item:${item}count:${count}andcost:${cost}totalvalue:${totalValue}`);
});
app.get('/',function(req,res){
res.render('insert');
});
app.listen(3000);
